### ISSUE TITLE
running scaffold on fresh project can error if models directory missing

### ISSUE THREAD

**Issue by brianleroux** [beginner-corp/cli#29] opened 2022-08-12 20:54 UTC
if models isn't there we should make it for em

![Screen Shot 2022-08-12 at 1 54 11 PM](https://user-images.githubusercontent.com/990/184443542-032803c4-ad55-47fc-a36d-ea9e66e6a83a.png)

**Comment by macdonst** [comment] 2022-08-15 01:09
@brianleroux huh, when you create a new project I do create the models directory. 

https://github.com/beginner-corp/cli/blob/main/src/commands/new/generators/project/action.js#L72

Did you by chance delete the folder before running `generate`? The only way I can reproduce it is by deleting the folder before running any other command. If you run `begin dev` after deleting the folder you get the same error.

**Comment by macdonst** [comment] 2022-08-15 01:16
Since the `arc-plugin-enhance` sets the shared folder to be `models` if you delete the folder, then inventory will complain.

**Comment by macdonst** [comment] 2022-08-15 17:12
`@architect/inventory` has a fix for this issue but we need to wait for a new version of `@architect/sandbox` to be released as well.

**Comment by macdonst** [comment] 2022-08-17 17:13
If I clean the `node_modules` and pin `@architect/inventory` to 3.2.1 I can generate a new error. 

To reproduce:

- build a version of the Begin CLI with inventory 3.2.1
- `begin new project --path today`
- `rm -rf models`
- `begin dev`

Then you will see the new error:

```
Error:
    at Object.mkdirSync (fs.js:1013:3)
    at mkdirSync (pkg/prelude/bootstrap.js:1508:33)
    at copy (/snapshot/cli/node_modules/@architect/hydrate/src/shared/copy.js:16:5)
    at Array.copier (/snapshot/cli/node_modules/@architect/hydrate/src/shared/copy-static-json.js:33:9)
    at runSeries (/snapshot/cli/node_modules/run-series/index.js:23:33)
    at copyStatic (/snapshot/cli/node_modules/@architect/hydrate/src/shared/copy-static-json.js:31:5)
    at Array.<anonymous> (/snapshot/cli/node_modules/@architect/hydrate/src/shared/index.js:59:7)
    at each (/snapshot/cli/node_modules/run-series/index.js:20:24)
    at print (/snapshot/cli/node_modules/@architect/hydrate/src/_printer.js:66:10)
    at _done (/snapshot/cli/node_modules/@architect/hydrate/src/shared/copy-views.js:39:12)
```

**Comment by macdonst** [comment] 2022-08-19 18:42
I've put in a guard to avoid this problem in v0.0.27 but have asked Ryan to take a look at what's going on as well.

**Closed by macdonst** 2022-08-19 18:42 UTC
