### ISSUE TITLE
When I deploy a new app it reports error

### ISSUE THREAD

**Issue by ryanbethel** [beginner-corp/cli#62] opened 2022-09-21 17:54 UTC
When I deploy a new app it reports app not found error. This may be because another build is stalled while building. I don't know how simultaneous builds affect each other.

```
➜  enhance.dev git:(test-begin-deploy) begin deploy
This project doesn't appear to be associated with a Begin app
? Would you like to create a Begin app based on this project? (Y/n) · true
? What would you like to name your app? · test-edotdev
? What would you like to name your first environment? · staging
Added appID 'RNMN9KHW' to project, be sure to commit this change!
Archived project in 317ms
Uploading project in 1 part
Error: app_not_found
➜  enhance.dev git:(test-begin-deploy) ✗
```

**Comment by ryanblock** [comment] 2022-09-21 17:56
Closing as duplicate of https://github.com/beginner-corp/cli/issues/55

**Closed by ryanblock** 2022-09-21 17:56 UTC
