### ISSUE TITLE
begin domains list command fails if there is an esm plugin in the project

### ISSUE THREAD

**Issue by ryanbethel** [beginner-corp/cli#162] opened 2023-08-12 11:08 UTC
Trying to list domains in a project where there is an esm plugin fails. This is a known bug for running the project with `begin dev`. But it does not seem like the domains list command should need to run the project in order to list domains. 

```
➜  otsd-app git:(main) ✗ begin update
Checking for latest version
Downloading https://dl.begin.com/releases/latest/begin-x64-darwin.zip (30.57 MiB)
Got 30.57 MiB of 30.57 MiB (100%)
Upgrading Begin to 0.17.0
Updated /Users/ryanbethel/.begin/begin
Successfully upgraded Begin!
➜  otsd-app git:(main) ✗ begin domains list
Error: Plugin error:
- Unable to load plugin 'authentication': ESM plugins not yet supported in Begin; for more information please see https://github.com/vercel/pkg/issues/1291
    at getPluginModules (/snapshot/cli/node_modules/@architect/inventory/src/config/pragmas/plugins.js)
    at getPluginModulesCallbackified (node:util:306:5)
    at architectInventory (/snapshot/cli/node_modules/@architect/inventory/src/index.js)
    at action (/snapshot/cli/src/commands/domains/index.js)
    at runCommand (/snapshot/cli/src/commands/index.js)
    at begin (/snapshot/cli/src/index.js)
    at Object.<anonymous> (/snapshot/cli/src/index.js)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
➜  otsd-app git:(main) ✗
```

**Comment by ryanbethel** [comment] 2023-08-17 16:18
@tbeseda Just curious if you have run into this or am I holding it wrong?

**Comment by ryanbethel** [comment] 2023-08-26 00:16
@tbeseda Just wondering if you saw this?

**Comment by ryanblock** [comment] 2023-08-26 04:36
I believe this would be expected per https://github.com/beginner-corp/cli/issues/154, no?

**Comment by macdonst** [comment] 2024-01-12 20:51
Closing this one as it is the same root cause as #154.

**Closed by macdonst** 2024-01-12 20:51 UTC
